name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy
- pocl
- pocl-cuda
- mako
- pyopencl
- islpy
- pyfmmlib
- mpi4py

# Only needed to make pylint succeed
- matplotlib-base

# This is intended to prevent conda from selecting 'external' (i.e. empty) builds
# of OpenMPI to satisfy the MPI dependency of mpi4py. It did so in May 2024, leading
# to confusing failues saying
# 'libmpi.so.40: cannot open shared object file: No such file or directory'.
# https://github.com/conda-forge/openmpi-feedstock/issues/153
# https://conda-forge.org/docs/user/tipsandtricks/#using-external-message-passing-interface-mpi-libraries
- openmpi>=5=h*
