name: test-conda-env
channels:
- conda-forge
- defaults

dependencies:
- python=3
- git
- conda-forge::numpy
- pocl
- mako
- pyopencl
- islpy
- pyfmmlib

# Only needed to make pylint succeed
- matplotlib

- pip
- pip:
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy

    # only for reference values for the fmmlib test
    # (unable to use--circular dep)
    # git+https://github.com/inducer/sumpy
