name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy
- pocl
- pocl-cuda
- mako
- pyopencl
- islpy
- pyfmmlib
- mpi4py

# Only needed to make pylint succeed
- matplotlib-base
