name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy

# https://github.com/pocl/pocl/issues/955
- pocl<=1.6

- pocl-cuda
- mako
- pyopencl
- islpy
- pyfmmlib
- mpi4py

# Only needed to make pylint succeed
- matplotlib-base
